name: Deploy Backend to EC2 (Test / Prod)

on:
  push:
    branches:
      - test
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Set Environment Variables (Test / Prod)
        run: |
          if [[ "${GITHUB_REF##*/}" == "prod" ]]; then
            echo "HOST=${{ secrets.PROD_HOST }}" >> $GITHUB_ENV
            echo "TARGET_DIR=${{ secrets.PROD_TARGET_DIR }}" >> $GITHUB_ENV
          else
            echo "HOST=${{ secrets.TEST_HOST }}" >> $GITHUB_ENV
            echo "TARGET_DIR=${{ secrets.TEST_TARGET_DIR }}" >> $GITHUB_ENV
          fi

      - name: SCP backend project to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no -r ./backend ${{ secrets.USERNAME }}@${{ env.HOST }}:${{ env.TARGET_DIR }}

      - name: SSH into EC2 and deploy
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ env.HOST }} << EOF
            cd $TARGET_DIR/backend
            chmod +x ./gradlew
            ./gradlew build
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker build -t backend .
            sudo docker run -d -p 8080:8080 --name backend backend
          EOF


